### ISSUE TITLE
First deployment of resource that executes `drush site-install` fails

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/quickstart-docker#13]
**Problem:**

The first deployment of the following resource fails:

```
exec::Run[vm1,command=bash -c 'cd /usr/share/drupal7; /usr/bin/drush site-install -y --account-mail=admin@example.com --account-name=admin --account-pass=test --site-name='localhost' --sites-subdir=localhost']
````

with the following error:

```
Starting Drupal installation. This takes a while. Consider using the        [ok]
--notify global option.
sendmail: fatal: parameter inet_interfaces: no local interface found for ::1
WD mail: Error sending e-mail (from admin@example.com to                 [error]
admin@example.com).
Installation complete.                                                      [ok]
Unable to send e-mail. Contact the site administrator if the problem     [error]
persists.
```

No `::1` interface is available in the container. The second deployment of that resource deploys successfully.

**Tasks:**

- [ ] Resolve the above-mentioned issue
- [ ] Update the `ci/do_test_deployment_and_verify.sh` script as such that it checks whether all resources deployed successfully. Currently the script validates the deployment by checking whether the `install.php` endpoint is available.

**Comment by bartv** [comment]
the quickstart has been replaced
