### ISSUE TITLE
Add support to deploy the quickstart on Centos8 containers

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/quickstart-docker#24]
An attempt was already done to migrate the agent containers to Centos8. We learned that the following changes are required with respect to the `agent/Dockerfile`:

- [ ] Update image source to `centos:8`
- [ ] Install the `glibc-locale-source` package to make the `localedef` command work
- [ ] Install the `python39` package and create a symlink from `/bin/python` to `/bin/python3`
- [ ] Update the `drupal` module as such that it is compatible with Centos8. The `php-drush-drush` and `drupal7` packages are not available in the `epel` repositories on Centos8.
- [ ] (Maybe others)

```
diff --git a/agent/Dockerfile b/agent/Dockerfile
index e718637..c589060 100644
--- a/agent/Dockerfile
+++ b/agent/Dockerfile
@@ -1,4 +1,4 @@
-FROM centos:7
+FROM centos:8
 ENV container docker
 RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
 systemd-tmpfiles-setup.service ] || rm -f $i; done); \
@@ -11,7 +11,8 @@ rm -f /lib/systemd/system/basic.target.wants/*;\
 rm -f /lib/systemd/system/anaconda.target.wants/*;
 VOLUME [ "/sys/fs/cgroup" ]
 
-RUN yum install -y openssh-server; yum clean all; systemctl enable sshd.service
+RUN yum install -y openssh-server glibc-locale-source python39; yum clean all; systemctl enable sshd.service
+RUN ln -s /bin/python3 /bin/python
 RUN mkdir /var/run/sshd
 
 RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
```

**Comment by bartv** [comment]
Guillaume is currently working on an improved inmanta container

**Comment by bartv** [comment]
the quickstart has been replaced
